apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
        - name: mysite
          image: 778841258598.dkr.ecr.eu-west-2.amazonaws.com/mysite:312da7d1999b03dba4f5e621df655cc7c5a543d5
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ecr-secret
